---
git_ssh_signing_enabled: true
git_ssh_signing_key: "~/.ssh/gh_sk.pub"
git_ssh_wrapper_dir: "~/.local/bin"
git_ssh_wrapper_path: "{{ git_ssh_wrapper_dir }}/git-ssh-wrapper"
git_ssh_prompt_message: ">> Touch hardware key to sign commit..."
git_ssh_allowed_signers_file: "~/.config/git/allowed_signers"
