- name: Set up local workstation
  hosts: local
  roles:
    - role: git
      become: false
      tags:
        - git
    - role: dnf
      become: true
      tags:
        - dnf
    - role: tmux
      tags:
        - tmux
      when: false
    - role: asdf
      become: false
      tags:
        - asdf
      when: false
    - role: python
      tags:
        - python
      when: false
    - role: terraform
      become: false
      tags:
        - terraform
      when: false
    - role: golang
      tags:
        - golang
      when: false
    - role: node
      tags:
        - node
      when: false
    - role: emacs
      become: false
      tags:
        - emacs
    - role: bash
      become: false
      tags:
        - bash
