- name: Install git
  ansible.builtin.dnf:
    name: git
    state: present
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  when: false

- name: Link global gitignore file
  ansible.builtin.file:
    src: '{{ dotfiles_home }}/roles/git/files/gitignore_global'
    dest: '{{ dotfiles_user_home }}/.gitignore_global'
    state: link
    force: true

- name: Check if gitconfig exists
  ansible.builtin.stat:
    path: "{{ dotfiles_user_home }}/.gitconfig"
  register: git_gitconfig_stat

- name: Back up gitconfig
  ansible.builtin.command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: '{{ dotfiles_user_home }}/.gitconfig.bak'
  when: git_gitconfig_stat.stat.exists

- name: Make sure gitconfig is up to date
  ansible.builtin.template:
    src: gitconfig.j2
    dest: '{{ dotfiles_user_home }}/.gitconfig'
    mode: '0644'

- name: Include SSH signing tasks
  ansible.builtin.include_tasks:
    file: ssh_signing.yml
  when: git_ssh_signing_enabled | bool
