---
- name: Install Node.js and npm
  ansible.builtin.dnf:
    name: nodejs
    state: present
  become: true
- name: Configure npm prefix to ~/.local in .npmrc
  ansible.builtin.lineinfile:
    path: "~/.npmrc"
    line: "prefix=~/.local"
    create: yes
    state: present
  become: false
