# -*- mode: shell-script -*-
# Enable the subsequent settings only in interactive sessions
case $- in
  *i*) ;;
    *) return;;
esac

# Path to your oh-my-bash installation.
export OSH="${HOME}/.dotfiles/oh-my-bash"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-bash is loaded.

# if running on aroma set the theme to powerbash10k
if [[ "$HOSTNAME" =~ ^aroma ]]; then
    OSH_THEME="powerbash10k"
else
    # OSH_THEME="powerline-icon"
    # OSH_THEME="powerline-plain"
    # OSH_THEME="primer"
    OSH_THEME="nekolight"
    # POWERLINE_PROMPT_USER_INFO_MODE="sudo"
fi

# Show Python virtual environment and conda environment
export THEME_SHOW_PYTHON=true

# Handle dumb terminals
if [[ "$TERM" == "dumb" ]]; then
    # Unset OSH's theme
    export OSH_THEME=""

    # Use a simple, standard prompt like "$" or "> "
    PS1='\$ '
fi

# Uncomment the following line to use case-sensitive completion.
# OMB_CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# OMB_HYPHEN_SENSITIVE="false"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_OSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you don't want the repository to be considered dirty
# if there are untracked files.
# SCM_GIT_DISABLE_UNTRACKED_DIRTY="true"

# Uncomment the following line if you want to completely ignore the presence
# of untracked files in the repository.
# SCM_GIT_IGNORE_UNTRACKED="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.  One of the following values can
# be used to specify the timestamp format.
# * 'mm/dd/yyyy'     # mm/dd/yyyy + time
# * 'dd.mm.yyyy'     # dd.mm.yyyy + time
# * 'yyyy-mm-dd'     # yyyy-mm-dd + time
# * '[mm/dd/yyyy]'   # [mm/dd/yyyy] + [time] with colors
# * '[dd.mm.yyyy]'   # [dd.mm.yyyy] + [time] with colors
# * '[yyyy-mm-dd]'   # [yyyy-mm-dd] + [time] with colors
# If not set, the default value is 'yyyy-mm-dd'.
# HIST_STAMPS='yyyy-mm-dd'

# Uncomment the following line if you do not want OMB to overwrite the existing
# aliases by the default OMB aliases defined in lib/*.sh
# OMB_DEFAULT_ALIASES="check"

# Would you like to use another custom folder than $OSH/custom?
# OSH_CUSTOM=/path/to/new-custom-folder

# To disable the uses of "sudo" by oh-my-bash, please set "false" to
# this variable.  The default behavior for the empty value is "true".
OMB_USE_SUDO=false
THEME_SHOW_SUDO=false

# To enable/disable display of Python virtualenv and condaenv
OMB_PROMPT_SHOW_PYTHON_VENV=true  # enable
# OMB_PROMPT_SHOW_PYTHON_VENV=false # disable

# Which completions would you like to load? (completions can be found in ~/.oh-my-bash/completions/*)
# Custom completions may be added to ~/.oh-my-bash/custom/completions/
# Example format: completions=(ssh git bundler gem pip pip3)
# Add wisely, as too many completions slow down shell startup.
completions=(
  git
  docker
  gh
  makefile
  kubectl
)

# Which aliases would you like to load? (aliases can be found in ~/.oh-my-bash/aliases/*)
# Custom aliases may be added to ~/.oh-my-bash/custom/aliases/
# Example format: aliases=(vagrant composer git-avh)
# Add wisely, as too many aliases slow down shell startup.
aliases=(
    general
    docker
)

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-bash/plugins/*)
# Custom plugins may be added to ~/.oh-my-bash/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  bashmarks
)

# Which plugins would you like to conditionally load? (plugins can be found in ~/.oh-my-bash/plugins/*)
# Custom plugins may be added to ~/.oh-my-bash/custom/plugins/
# Example format:
#  if [ "$DISPLAY" ] || [ "$SSH" ]; then
#      plugins+=(tmux-autoattach)
#  fi
source "$OSH"/oh-my-bash.sh

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='emacs -nw'
else
  export EDITOR='emacs -nw'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-bash libs,
# plugins, and themes. Aliases can be placed here, though oh-my-bash
# users are encouraged to define aliases within the OSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias bashconfig="mate ~/.bashrc"
# alias ohmybash="mate ~/.oh-my-bash"

# Personal Configuration

export LSP_USE_PLISTS=true
export TEMP="${HOME}/tmp/"
export EDITOR='emacs -nw'
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
export TODO_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/todo"
export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S  "
export SOPS_AGE_KEY_FILE="${HOME}/.config/sops/age/keys.txt"
GPG_TTY=$(tty)
export GPG_TTY

# source "${HOME}/.bashrc.secrets"

# shopts
set +o noclobber

# if macosx disable autocd and dirspell
if [[ "$OSTYPE" != "darwin"* ]]; then
  shopt -s autocd
  shopt -s dirspell
fi
shopt -u histreedit
shopt -u histverify
shopt -u lithist
shopt -u nocaseglob
shopt -u nocasematch

# unalias oh-my-bash stuff
unalias g
unalias p
unalias d

# aliases
alias a=alias
alias fcd=qcd
alias fem="fzf --preview 'bat --color=always {}' --preview-window '~3' --bind 'enter:become(emacs {})'"
alias fh="history | fzf"
alias fpv="fzf --preview 'bat --color=always {}' --preview-window '~3'"
alias g=gcloud
alias jf='sudo journalctl --follow'
alias qpv=fpv
alias jcli=jenkins-cli
alias task=go-task

alias jmp='ssh k8s-jumpserver'
alias c1='ssh k8s-control-01'
alias w1='ssh k8s-worker-01'
alias w2='ssh k8s-worker-02'

alias open='xdg-open'
alias di='sudo dnf install'
alias diy='sudo dnf install -y'
alias fa='alias|fzf'

# ssh aliases
alias sshp=sshp.sh
alias getip=getip.sh
alias m01='sshp m01'
alias a01='ssh a01'

# system/admin
alias s='sudo systemctl'
alias specs='fastfetch --localip-show-all-ips --localip-show-loop'

# development
alias gcsheet='gcloud cheat-sheet'
alias pyact='source .venv/bin/activate'

# networking
alias lsock='sudo lsof -i -P'                   # lsock:        Display open sockets
alias lsockU='sudo lsof -nP | grep UDP'         # lsockU:       Display only open UDP sockets
alias lsockT='sudo lsof -nP | grep TCP'         # lsockT:       Display only open TCP sockets
alias openPorts='sudo lsof -i | grep LISTEN'    # openPorts:    All listening connections
alias openp='sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections

# date and time
alias cal3='cal -3'
alias epochtime='date +%s'
alias mytime='date +%H:%M:%S'
alias tstamp='date "+%Y%m%dT%H%M%S"'
alias today='date +"%A, %B %-d, %Y"'
alias weeknum='date +%V'

# hosts
alias ai='ssh aroma'
alias aroma='ssh aroma'

# Wayland
alias wp="waypipe -c lz4=9 ssh aroma"

# security
alias check="dnf check-update --refresh"
# alias update="sudo dnf update --refresh -y; flatpak update -y; npm install -g @google/gemini-cli@latest"
alias dhi="dnf history info"
alias dhl="dnf history list | fzf --preview 'dnf history info {1}' --preview-window=right:50% | awk '{print $1}' | xargs -I {} dnf history info {}"
alias scan='sudo freshclam; clamscan -o -a -r'

# container development
alias usU="podman unshare chown -R $(id -u):$(id -g) ."
alias us0='podman unshare chown -R 0:0 .'
alias gemcli='SANDBOX_FLAGS="--userns=keep-id --network=slirp4netns" gemini -s'
alias update-gemcli='npm install -g @google/gemini-cli@latest'

# jenkins and datadog container management aliases
alias jclean='podman stop jenkins_server; sleep 4; podman container rm jenkins_server'
alias dclean='podman stop datadog_agent; sleep 4; podman rm datadog_agent'

# emacs
alias ec='emacsclient -c -n'
alias quicknote='function _qn() { emacsclient "org-protocol://capture?template=N&url=shell&title=QuickNote&body=$1"; }; _qn'

# apps
alias brave='flatpak run com.brave.Browser'

# functions
gitrealclean() {
    # 1. Determine the default branch name
    local default_branch
    default_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
    default_branch=${default_branch:-main}

    # 2. Get the most recent non-default branch
    local recent_branch
    recent_branch=$(git for-each-ref --sort=-committerdate refs/heads/ \
        --count=1 \
        --format='%(refname:short)' \
        --exclude="refs/heads/$default_branch")

    if [ -z "$recent_branch" ]; then
        echo "No non-default branches found to delete."
        return 1
    fi

    # 3. Execute the cleanup
    echo "Switching to $default_branch and deleting $recent_branch..."
    git switch "$default_branch" && \
    git pull && \
    git branch -d "$recent_branch"
}

# Capture stdout to Emacs Org-Inbox
# Usage: ls -la | emacspipe "Folder Listing"
emacspipe() {
    local title="${1:-CLI Capture}"
    # local body
    # body=$(cat) # Read from stdin

    # URL encode the body using python
    local encoded_body
    encoded_body=$(python3 -c "import sys, urllib.parse; print(urllib.parse.quote(sys.stdin.read()))")
    emacsclient "org-protocol://capture?template=N&url=shell-pipe&title=${title}&body=${encoded_body}"
}

las(){
    local -r pflg="$1"
    local cmd='echo {} | awk -F"[^[:alnum:]]+" "{print \$2}"'

    if [[ "$pflg" == 'a' ]];then
        local bindcmd="enter:become(echo {})"
    else
        local bindcmd="enter:become($cmd)"
    fi

    an_alias=$(an_alias | fzf --preview 'bat --color=always {}' --preview-window '~3' --bind "$bindcmd")
    local an_alias

    if [[ "$pflg" =~ (a|p) ]] ;then
        echo "$an_alias"
    else
        eval "$an_alias"
    fi
}

## A function that changes the k8 namespace
function k8cluster() {
    if [ -z "$1" ]; then
        kubectx -c
        return 0
    fi

    kubectx "$1"
}

## A function that list the current namespace
function k8listcluster() {
    kubectx
}

## A function that changes the k8 namespace
function k8ns() {
    if [ -z "$1" ]; then
        kubectl get namespaces
        return 0
    fi
    kubectl config set-context --current --namespace="$1"
}

## A function that list the current namespace
function k8listns() {
    kubectl config view --minify | grep namespace: | awk '{print $2}'
}

## A function obtains a shell on a running container
function k8sh() {
    # Set pod name
    if [ -z "$1" ]; then
        echo "Usage: k8sh <pod-name> <container-name>"
        return 1
    fi

    # Set container name
    if [ -z "$2" ]; then
        echo "Usage: k8sh <pod-name> <container-name>"
        return 1
    fi

    # Select command to run
    cmd="$3"
    if [ -z "$cmd" ]; then
        cmd="/bin/bash"
    fi

    kubectl exec -it "$1" -c "$2" -- sh -c $"$cmd"
}

## A function that quickly cd's to a directory
function qcd() {
    if [ -z "$1" ]; then
        start_dir=.
    else
        start_dir="$1"
    fi

    cd "$(fd --type directory . "$start_dir" | fzf)" || return 1
}

function vterm_printf() {
    if [ -n "$TMUX" ] && ([ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ]); then
        # Tell tmux to pass the escape sequences through
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    function clear() {
        vterm_printf "51;Evterm-clear-scrollback";
        tput clear;
    }
    function vterm_set_directory() {
        vterm_printf "51;A%s" "$(pwd)"
    }
    export PROMPT_COMMAND="vterm_set_directory; ${PROMPT_COMMAND}"
fi

function frg(){
    rg --line-number --with-filename . --color=always --field-match-separator ' '\
        | fzf --preview "bat --color=always {1} --highlight-line {2}" \
              --preview-window ~8,+{2}-5
}

function update() {
    printf "=============== Update dnf ===========================\n"
    sudo dnf update --refresh -y
    printf "=============== Update flatpack ======================\n"
    flatpak update -y
    # printf "=============== Update Gemini CLI ====================\n"
    # npm install -g @google/gemini-cli@latest
    # printf "=============== Update Gemini Custom Sandbox =========\n"
    # pushd "${HOME}/git/personal/gemini-custom-sandbox/" || return
    # task build
    # popd || return
}

#source <(op completion bash)

if [[ "$OSTYPE" == "darwin"* ]]; then
    export JAVA_HOME=/usr/local/opt/openjdk@17
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    export JAVA_HOME="/usr/lib/jvm/java-21-openjdk"
    export PATH="$PATH:$JAVA_HOME/bin"
fi

export CLOUDSDK_PYTHON=/usr/bin/python3.13

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:#89e76a,fg+:#ffd000,bg:#191919,bg+:#262626
  --color=hl:#00f6f6,hl+:#b0faff,info:#afaf87,marker:#87ff00
  --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff,header:#87afaf
  --color=border:#262626,label:#aeaeae,query:#d9d9d9
  --border="rounded" --border-label="" --preview-window="border-rounded" --prompt="> "
  --marker=">" --pointer="◆" --separator="─" --scrollbar="│"'


# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Set up fzf key bindings and fuzzy completion
FZF_CTRL_T_COMMAND=""
if [ -x "$(command -v fzf)"  ]
then
    source /usr/share/fzf/shell/key-bindings.bash
fi

# # Set up gcloud auto complete
if [[ "$HOSTNAME" =~ ^penguin ]]; then
    if [ -f "/usr/share/google-cloud-sdk/completion.bash.inc" ]; then
        source /usr/share/google-cloud-sdk/completion.bash.inc
    fi
fi

# # Make sure 'g' alias to 'gcloud' works as well
_gcloud_alias_completion() {
    _python_argcomplete gcloud "$@"
}
complete -o default -F _gcloud_alias_completion g


# if kubectl is found source the completion and setup aliases
if command -v kubectl &> /dev/null; then
    source <(kubectl completion bash)
    alias k=kubectl
    complete -o default -F __start_kubectl k
fi
export PATH="$PATH:${HOME}/.cargo/bin:${KREW_ROOT:-$HOME/.krew}/bin"

# uv
export PATH="/home/slams/.local/bin:$PATH"

# zoxide
eval "$(zoxide init bash)"
